# Clock from simulation
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# PointCloud2 from LiDAR
- ros_topic_name: "lidar/points"
  gz_topic_name: "lidar/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  lazy: true
  direction: GZ_TO_ROS

# Odometry from DiffDrive system
- ros_topic_name: "odom"
  gz_topic_name: "world/default/model/my_robot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  lazy: false
  direction: GZ_TO_ROS

# TF from DiffDrive (Pose publisher)
- ros_topic_name: "tf"
  gz_topic_name: "/model/my_robot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Velocity commands to DiffDrive
- ros_topic_name: "cmd_vel"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Joint states from JointStatePublisher system
- ros_topic_name: "joint_states"
  gz_topic_name: "world/default/model/my_robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
